SELECT *
  FROM(SELECT ROW_NUMBER() OVER(ORDER BY COUNT(QUIZ_NUMBER) DESC) AS RNO,
			   QUIZ_NUMBER,
			   QUIZ_TITLE
		  FROM QUIZ)
          WHERE RNO BETWEEN 1 AND 10; 
          
          
INSERT INTO QUIZ VALUES(2, '生生生生生', SYSDATE, NULL, 2, 1);
INSERT INTO QUIZ VALUES(3, '生生生生生', SYSDATE, NULL, 2, 1);
INSERT INTO QUIZ VALUES(4, '生生生生生', SYSDATE, NULL, 2, 1);
INSERT INTO QUIZ VALUES(5, '生生生生生', SYSDATE, NULL, 2, 1);
INSERT INTO QUIZ VALUES(6, '生生生生生', SYSDATE, NULL, 2, 1);
INSERT INTO QUIZ VALUES(7, '生生生生生', SYSDATE, NULL, 2, 1);
INSERT INTO QUIZ VALUES(8, '生生生生生', SYSDATE, NULL, 2, 1);
INSERT INTO QUIZ VALUES(9, '生生生生生', SYSDATE, NULL, 2, 1);
INSERT INTO QUIZ VALUES(10, '生生生生生', SYSDATE, NULL, 2, 1);
COMMIT;