INSERT INTO COMMUNITY_TAB (TAB_NUMBER, TAB_NAME) 
VALUES (1, '공지');

INSERT INTO COMMUNITY_TAB (TAB_NUMBER, TAB_NAME) 
VALUES (2, '잡담');

INSERT INTO COMMUNITY_TAB (TAB_NUMBER, TAB_NAME) 
VALUES (3, '질문');

INSERT INTO COMMUNITY_TAB (TAB_NUMBER, TAB_NAME) 
VALUES (4, '풀이');


INSERT INTO MEMBER  
VALUES (1, 'admin', 'admin', '관리자', 0, NULL, to_date('09/21/2024', 'MM/DD/RRRR'), 4, 'Y', '관리자 계정', NULL, NULL, NULL);

INSERT INTO MEMBER
VALUES (2, 'user01', 'pass01', 'test01', 0, '/static/img/userProfile/test.png', to_date('09/21/2024', 'MM/DD/RRRR'), 3, 'Y', '안녕하세요. 잘부탁드립니다.', NULL, NULL, NULL);

INSERT INTO MEMBER
VALUES (3, 'user02', 'pass02', 'test02', 0, '/static/img/userProfile/test.png', to_date('09/21/2024', 'MM/DD/RRRR'), 0, 'Y', '안녕하세요. 잘부탁드립니다.', NULL, NULL, NULL);

INSERT INTO MEMBER
VALUES (4, 'user03', 'pass03', 'test03', 0, '/static/img/userProfile/test.png', to_date('09/21/2024', 'MM/DD/RRRR'), 0, 'Y', '안녕하세요. 잘부탁드립니다.', NULL, NULL, NULL);

INSERT INTO MEMBER
VALUES (5, 'user04', 'pass04', 'test04', 0, '/static/img/userProfile/test.png', to_date('09/21/2024', 'MM/DD/RRRR'), 0, 'Y', '안녕하세요. 잘부탁드립니다.', NULL, NULL, NULL);

INSERT INTO MEMBER
VALUES (6, 'user05', 'pass05', 'test05', 0, '/static/img/userProfile/test.png', to_date('09/21/2024', 'MM/DD/RRRR'), 0, 'Y', '안녕하세요. 잘부탁드립니다.', NULL, NULL, NULL);

insert into DAILY_CHECK values(1, sysdate-4, 1);
insert into DAILY_CHECK values(2, sysdate-4, 2);
insert into DAILY_CHECK values(3, sysdate-3, 1);
insert into DAILY_CHECK values(4, sysdate-3, 2);
insert into DAILY_CHECK values(5, sysdate-2, 1);
insert into DAILY_CHECK values(6, sysdate-2, 2);
insert into DAILY_CHECK values(7, sysdate-1, 1);


INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (1, '안녕하세요1', '반갑습니다~~1', 2, 0, to_date('01/01/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (2, '안녕하세요2', '반갑습니다~~2', 3, 0, to_date('01/02/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (3, '안녕하세요3', '반갑습니다~~3', 4, 0, to_date('01/03/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (4, '안녕하세요4', '반갑습니다~~4', 2, 0, to_date('01/04/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (5, '안녕하세요5', '반갑습니다~~5', 3, 0, to_date('01/05/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (6, '안녕하세요6', '반갑습니다~~6', 4, 0, to_date('01/06/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (7, '안녕하세요7', '반갑습니다~~7', 2, 0, to_date('01/07/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (8, '안녕하세요8', '반갑습니다~~8', 3, 0, to_date('01/08/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (9, '안녕하세요9', '반갑습니다~~9', 4, 0, to_date('01/09/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (10, '안녕하세요10', '반갑습니다~~10', 2, 0, to_date('01/10/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (11, '안녕하세요11', '반갑습니다~~11', 3, 0, to_date('01/11/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (12, '안녕하세요12', '반갑습니다~~12', 4, 0, to_date('01/12/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (13, '안녕하세요13', '반갑습니다~~13', 2, 0, to_date('01/13/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (14, '안녕하세요14', '반갑습니다~~14', 3, 0, to_date('01/14/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (15, '안녕하세요15', '반갑습니다~~15', 4, 0, to_date('01/15/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (16, '안녕하세요16', '반갑습니다~~16', 2, 0, to_date('01/16/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (17, '안녕하세요17', '반갑습니다~~17', 3, 0, to_date('01/17/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (18, '안녕하세요18', '반갑습니다~~18', 4, 0, to_date('01/18/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (19, '안녕하세요19', '반갑습니다~~19', 2, 0, to_date('01/19/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (20, '안녕하세요20', '반갑습니다~~20', 3, 0, to_date('01/20/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (21, '안녕하세요21', '반갑습니다~~21', 4, 0, to_date('01/21/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (22, '안녕하세요22', '반갑습니다~~22', 2, 0, to_date('01/22/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (23, '안녕하세요23', '반갑습니다~~23', 3, 0, to_date('01/23/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (24, '안녕하세요24', '반갑습니다~~24', 4, 0, to_date('01/24/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (25, '안녕하세요25', '반갑습니다~~25', 2, 0, to_date('01/25/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (26, '안녕하세요26', '반갑습니다~~26', 3, 0, to_date('01/26/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (27, '안녕하세요27', '반갑습니다~~27', 4, 0, to_date('01/27/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (28, '안녕하세요28', '반갑습니다~~28', 2, 0, to_date('01/28/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (29, '안녕하세요29', '반갑습니다~~29', 3, 0, to_date('01/29/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (30, '안녕하세요30', '반갑습니다~~30', 4, 0, to_date('01/30/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (31, '안녕하세요31', '반갑습니다~~31', 2, 0, to_date('01/31/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (32, '안녕하세요32', '반갑습니다~~32', 3, 0, to_date('02/01/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (33, '안녕하세요33', '반갑습니다~~33', 4, 0, to_date('02/02/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (34, '안녕하세요34', '반갑습니다~~34', 2, 0, to_date('02/03/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (35, '안녕하세요35', '반갑습니다~~35', 3, 0, to_date('02/04/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (36, '안녕하세요36', '반갑습니다~~36', 4, 0, to_date('02/05/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (37, '안녕하세요37', '반갑습니다~~37', 2, 0, to_date('02/06/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (38, '안녕하세요38', '반갑습니다~~38', 3, 0, to_date('02/07/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (39, '안녕하세요39', '반갑습니다~~39', 4, 0, to_date('02/08/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (40, '안녕하세요40', '반갑습니다~~40', 2, 0, to_date('02/09/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (41, '안녕하세요41', '반갑습니다~~41', 3, 0, to_date('02/10/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (42, '안녕하세요42', '반갑습니다~~42', 4, 0, to_date('02/11/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (43, '안녕하세요43', '반갑습니다~~43', 2, 0, to_date('02/12/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (44, '안녕하세요44', '반갑습니다~~44', 3, 0, to_date('02/13/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (45, '안녕하세요45', '반갑습니다~~45', 4, 0, to_date('02/14/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (46, '안녕하세요46', '반갑습니다~~46', 2, 0, to_date('02/15/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (47, '안녕하세요47', '반갑습니다~~47', 3, 0, to_date('02/16/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (48, '안녕하세요48', '반갑습니다~~48', 4, 0, to_date('02/17/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (49, '안녕하세요49', '반갑습니다~~49', 2, 0, to_date('02/18/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (50, '안녕하세요50', '반갑습니다~~50', 3, 0, to_date('02/19/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (51, '안녕하세요51', '반갑습니다~~51', 4, 0, to_date('02/20/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (52, '안녕하세요52', '반갑습니다~~52', 2, 0, to_date('02/21/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (53, '안녕하세요53', '반갑습니다~~53', 3, 0, to_date('02/22/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (54, '안녕하세요54', '반갑습니다~~54', 4, 0, to_date('02/23/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (55, '안녕하세요55', '반갑습니다~~55', 2, 0, to_date('02/24/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (56, '안녕하세요56', '반갑습니다~~56', 3, 0, to_date('02/25/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (57, '안녕하세요57', '반갑습니다~~57', 4, 0, to_date('02/26/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (58, '안녕하세요58', '반갑습니다~~58', 2, 0, to_date('02/27/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (59, '안녕하세요59', '반갑습니다~~59', 3, 0, to_date('02/28/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (60, '안녕하세요60', '반갑습니다~~60', 4, 0, to_date('02/29/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (61, '안녕하세요61', '반갑습니다~~61', 2, 0, to_date('03/01/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (62, '안녕하세요62', '반갑습니다~~62', 3, 0, to_date('03/02/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (63, '안녕하세요63', '반갑습니다~~63', 4, 0, to_date('03/03/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (64, '안녕하세요64', '반갑습니다~~64', 2, 0, to_date('03/04/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (65, '안녕하세요65', '반갑습니다~~65', 3, 0, to_date('03/05/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (66, '안녕하세요66', '반갑습니다~~66', 4, 0, to_date('03/06/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (67, '안녕하세요67', '반갑습니다~~67', 2, 0, to_date('03/07/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (68, '안녕하세요68', '반갑습니다~~68', 3, 0, to_date('03/08/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (69, '안녕하세요69', '반갑습니다~~69', 4, 0, to_date('03/09/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (70, '안녕하세요70', '반갑습니다~~70', 2, 0, to_date('03/10/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (71, '안녕하세요71', '반갑습니다~~71', 3, 0, to_date('03/11/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (72, '안녕하세요72', '반갑습니다~~72', 4, 0, to_date('03/12/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (73, '안녕하세요73', '반갑습니다~~73', 2, 0, to_date('03/13/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (74, '안녕하세요74', '반갑습니다~~74', 3, 0, to_date('03/14/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (75, '안녕하세요75', '반갑습니다~~75', 4, 0, to_date('03/15/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (76, '안녕하세요76', '반갑습니다~~76', 2, 0, to_date('03/16/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (77, '안녕하세요77', '반갑습니다~~77', 3, 0, to_date('03/17/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (78, '안녕하세요78', '반갑습니다~~78', 4, 0, to_date('03/18/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (79, '안녕하세요79', '반갑습니다~~79', 2, 0, to_date('03/19/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (80, '안녕하세요80', '반갑습니다~~80', 3, 0, to_date('03/20/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (81, '안녕하세요81', '반갑습니다~~81', 4, 0, to_date('03/21/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (82, '안녕하세요82', '반갑습니다~~82', 2, 0, to_date('03/22/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (83, '안녕하세요83', '반갑습니다~~83', 3, 0, to_date('03/23/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (84, '안녕하세요84', '반갑습니다~~84', 4, 0, to_date('03/24/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (85, '안녕하세요85', '반갑습니다~~85', 2, 0, to_date('03/25/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (86, '안녕하세요86', '반갑습니다~~86', 3, 0, to_date('03/26/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (87, '안녕하세요87', '반갑습니다~~87', 4, 0, to_date('03/27/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (88, '안녕하세요88', '반갑습니다~~88', 2, 0, to_date('03/28/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (89, '안녕하세요89', '반갑습니다~~89', 3, 0, to_date('03/29/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (90, '안녕하세요90', '반갑습니다~~90', 4, 0, to_date('03/30/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (91, '안녕하세요91', '반갑습니다~~91', 2, 0, to_date('03/31/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (92, '안녕하세요92', '반갑습니다~~92', 3, 0, to_date('04/01/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (93, '안녕하세요93', '반갑습니다~~93', 4, 0, to_date('04/02/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (94, '안녕하세요94', '반갑습니다~~94', 2, 0, to_date('04/03/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (95, '안녕하세요95', '반갑습니다~~95', 3, 0, to_date('04/04/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (96, '안녕하세요96', '반갑습니다~~96', 4, 0, to_date('04/05/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (97, '안녕하세요97', '반갑습니다~~97', 2, 0, to_date('04/06/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (98, '안녕하세요98', '반갑습니다~~98', 3, 0, to_date('04/07/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (99, '안녕하세요99', '반갑습니다~~99', 4, 0, to_date('04/08/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (100, '안녕하세요100', '반갑습니다~~100', 2, 0, to_date('04/09/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (101, '안녕하세요101', '반갑습니다~~101', 3, 0, to_date('04/10/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (102, '안녕하세요102', '반갑습니다~~102', 4, 0, to_date('04/11/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (103, '안녕하세요103', '반갑습니다~~103', 2, 0, to_date('04/12/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (104, '안녕하세요104', '반갑습니다~~104', 3, 0, to_date('04/13/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (105, '안녕하세요105', '반갑습니다~~105', 4, 0, to_date('04/14/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (106, '안녕하세요106', '반갑습니다~~106', 2, 0, to_date('04/15/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (107, '안녕하세요107', '반갑습니다~~107', 3, 0, to_date('04/16/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (108, '안녕하세요108', '반갑습니다~~108', 4, 0, to_date('04/17/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (109, '안녕하세요109', '반갑습니다~~109', 2, 0, to_date('04/18/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (110, '안녕하세요110', '반갑습니다~~110', 3, 0, to_date('04/19/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (111, '안녕하세요111', '반갑습니다~~111', 4, 0, to_date('04/20/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (112, '안녕하세요112', '반갑습니다~~112', 2, 0, to_date('04/21/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (113, '안녕하세요113', '반갑습니다~~113', 3, 0, to_date('04/22/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (114, '안녕하세요114', '반갑습니다~~114', 4, 0, to_date('04/23/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (115, '안녕하세요115', '반갑습니다~~115', 2, 0, to_date('04/24/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (116, '안녕하세요116', '반갑습니다~~116', 3, 0, to_date('04/25/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (117, '안녕하세요117', '반갑습니다~~117', 4, 0, to_date('04/26/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (118, '안녕하세요118', '반갑습니다~~118', 2, 0, to_date('04/27/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (119, '안녕하세요119', '반갑습니다~~119', 3, 0, to_date('04/28/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (120, '안녕하세요120', '반갑습니다~~120', 4, 0, to_date('04/29/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (121, '안녕하세요121', '반갑습니다~~121', 2, 0, to_date('04/30/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (122, '안녕하세요122', '반갑습니다~~122', 3, 0, to_date('05/01/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (123, '안녕하세요123', '반갑습니다~~123', 4, 0, to_date('05/02/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (124, '안녕하세요124', '반갑습니다~~124', 2, 0, to_date('05/03/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (125, '안녕하세요125', '반갑습니다~~125', 3, 0, to_date('05/04/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (126, '안녕하세요126', '반갑습니다~~126', 4, 0, to_date('05/05/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (127, '안녕하세요127', '반갑습니다~~127', 2, 0, to_date('05/06/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (128, '안녕하세요128', '반갑습니다~~128', 3, 0, to_date('05/07/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (129, '안녕하세요129', '반갑습니다~~129', 4, 0, to_date('05/08/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (130, '안녕하세요130', '반갑습니다~~130', 2, 0, to_date('05/09/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (131, '안녕하세요131', '반갑습니다~~131', 3, 0, to_date('05/10/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (132, '안녕하세요132', '반갑습니다~~132', 4, 0, to_date('05/11/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (133, '안녕하세요133', '반갑습니다~~133', 2, 0, to_date('05/12/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (134, '안녕하세요134', '반갑습니다~~134', 3, 0, to_date('05/13/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (135, '안녕하세요135', '반갑습니다~~135', 4, 0, to_date('05/14/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (136, '안녕하세요136', '반갑습니다~~136', 2, 0, to_date('05/15/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (137, '안녕하세요137', '반갑습니다~~137', 3, 0, to_date('05/16/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (138, '안녕하세요138', '반갑습니다~~138', 4, 0, to_date('05/17/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (139, '안녕하세요139', '반갑습니다~~139', 2, 0, to_date('05/18/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (140, '안녕하세요140', '반갑습니다~~140', 3, 0, to_date('05/19/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (141, '안녕하세요141', '반갑습니다~~141', 4, 0, to_date('05/20/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (142, '안녕하세요142', '반갑습니다~~142', 2, 0, to_date('05/21/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (143, '안녕하세요143', '반갑습니다~~143', 3, 0, to_date('05/22/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (144, '안녕하세요144', '반갑습니다~~144', 4, 0, to_date('05/23/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (145, '안녕하세요145', '반갑습니다~~145', 2, 0, to_date('05/24/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (146, '안녕하세요146', '반갑습니다~~146', 3, 0, to_date('05/25/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (147, '안녕하세요147', '반갑습니다~~147', 4, 0, to_date('05/26/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (148, '안녕하세요148', '반갑습니다~~148', 2, 0, to_date('05/27/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (149, '안녕하세요149', '반갑습니다~~149', 3, 0, to_date('05/28/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (150, '안녕하세요150', '반갑습니다~~150', 4, 0, to_date('05/29/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (151, '안녕하세요151', '반갑습니다~~151', 2, 0, to_date('05/30/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (152, '안녕하세요152', '반갑습니다~~152', 3, 0, to_date('05/31/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (153, '안녕하세요153', '반갑습니다~~153', 4, 0, to_date('06/01/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (154, '안녕하세요154', '반갑습니다~~154', 2, 0, to_date('06/02/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (155, '안녕하세요155', '반갑습니다~~155', 3, 0, to_date('06/03/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (156, '안녕하세요156', '반갑습니다~~156', 4, 0, to_date('06/04/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (157, '안녕하세요157', '반갑습니다~~157', 2, 0, to_date('06/05/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (158, '안녕하세요158', '반갑습니다~~158', 3, 0, to_date('06/06/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (159, '안녕하세요159', '반갑습니다~~159', 4, 0, to_date('06/07/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (160, '안녕하세요160', '반갑습니다~~160', 2, 0, to_date('06/08/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (161, '안녕하세요161', '반갑습니다~~161', 3, 0, to_date('06/09/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (162, '안녕하세요162', '반갑습니다~~162', 4, 0, to_date('06/10/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (163, '안녕하세요163', '반갑습니다~~163', 2, 0, to_date('06/11/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (164, '안녕하세요164', '반갑습니다~~164', 3, 0, to_date('06/12/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (165, '안녕하세요165', '반갑습니다~~165', 4, 0, to_date('06/13/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (166, '안녕하세요166', '반갑습니다~~166', 2, 0, to_date('06/14/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (167, '안녕하세요167', '반갑습니다~~167', 3, 0, to_date('06/15/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (168, '안녕하세요168', '반갑습니다~~168', 4, 0, to_date('06/16/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (169, '안녕하세요169', '반갑습니다~~169', 2, 0, to_date('06/17/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (170, '안녕하세요170', '반갑습니다~~170', 3, 0, to_date('06/18/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (171, '안녕하세요171', '반갑습니다~~171', 4, 0, to_date('06/19/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (172, '안녕하세요172', '반갑습니다~~172', 2, 0, to_date('06/20/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (173, '안녕하세요173', '반갑습니다~~173', 3, 0, to_date('06/21/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (174, '안녕하세요174', '반갑습니다~~174', 4, 0, to_date('06/22/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (175, '안녕하세요175', '반갑습니다~~175', 2, 0, to_date('06/23/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (176, '안녕하세요176', '반갑습니다~~176', 3, 0, to_date('06/24/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (177, '안녕하세요177', '반갑습니다~~177', 4, 0, to_date('06/25/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (178, '안녕하세요178', '반갑습니다~~178', 2, 0, to_date('06/26/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (179, '안녕하세요179', '반갑습니다~~179', 3, 0, to_date('06/27/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (180, '안녕하세요180', '반갑습니다~~180', 4, 0, to_date('06/28/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (181, '안녕하세요181', '반갑습니다~~181', 2, 0, to_date('06/29/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (182, '안녕하세요182', '반갑습니다~~182', 3, 0, to_date('06/30/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (183, '안녕하세요183', '반갑습니다~~183', 4, 0, to_date('07/01/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (184, '안녕하세요184', '반갑습니다~~184', 2, 0, to_date('07/02/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (185, '안녕하세요185', '반갑습니다~~185', 3, 0, to_date('07/03/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (186, '안녕하세요186', '반갑습니다~~186', 4, 0, to_date('07/04/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (187, '안녕하세요187', '반갑습니다~~187', 2, 0, to_date('07/05/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (188, '안녕하세요188', '반갑습니다~~188', 3, 0, to_date('07/06/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (189, '안녕하세요189', '반갑습니다~~189', 4, 0, to_date('07/07/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (190, '안녕하세요190', '반갑습니다~~190', 2, 0, to_date('07/08/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (191, '안녕하세요191', '반갑습니다~~191', 3, 0, to_date('07/09/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (192, '안녕하세요192', '반갑습니다~~192', 4, 0, to_date('07/10/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (193, '안녕하세요193', '반갑습니다~~193', 2, 0, to_date('07/11/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (194, '안녕하세요194', '반갑습니다~~194', 3, 0, to_date('07/12/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (195, '안녕하세요195', '반갑습니다~~195', 4, 0, to_date('07/13/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (196, '안녕하세요196', '반갑습니다~~196', 2, 0, to_date('07/14/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (197, '안녕하세요197', '반갑습니다~~197', 3, 0, to_date('07/15/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (198, '안녕하세요198', '반갑습니다~~198', 4, 0, to_date('07/16/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (199, '안녕하세요199', '반갑습니다~~199', 2, 0, to_date('07/17/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (200, '안녕하세요200', '반갑습니다~~200', 3, 0, to_date('07/18/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (201, '안녕하세요201', '반갑습니다~~201', 4, 0, to_date('07/19/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (202, '안녕하세요202', '반갑습니다~~202', 2, 0, to_date('07/20/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (203, '안녕하세요203', '반갑습니다~~203', 3, 0, to_date('07/21/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (204, '안녕하세요204', '반갑습니다~~204', 4, 0, to_date('07/22/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (205, '안녕하세요205', '반갑습니다~~205', 2, 0, to_date('07/23/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (206, '안녕하세요206', '반갑습니다~~206', 3, 0, to_date('07/24/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (207, '안녕하세요207', '반갑습니다~~207', 4, 0, to_date('07/25/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (208, '안녕하세요208', '반갑습니다~~208', 2, 0, to_date('07/26/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (209, '안녕하세요209', '반갑습니다~~209', 3, 0, to_date('07/27/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (210, '안녕하세요210', '반갑습니다~~210', 4, 0, to_date('07/28/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (211, '안녕하세요211', '반갑습니다~~211', 2, 0, to_date('07/29/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (212, '안녕하세요212', '반갑습니다~~212', 3, 0, to_date('07/30/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (213, '안녕하세요213', '반갑습니다~~213', 4, 0, to_date('07/31/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (214, '안녕하세요214', '반갑습니다~~214', 2, 0, to_date('08/01/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (215, '안녕하세요215', '반갑습니다~~215', 3, 0, to_date('08/02/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (216, '안녕하세요216', '반갑습니다~~216', 4, 0, to_date('08/03/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (217, '안녕하세요217', '반갑습니다~~217', 2, 0, to_date('08/04/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (218, '안녕하세요218', '반갑습니다~~218', 3, 0, to_date('08/05/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (219, '안녕하세요219', '반갑습니다~~219', 4, 0, to_date('08/06/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (220, '안녕하세요220', '반갑습니다~~220', 2, 0, to_date('08/07/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (221, '안녕하세요221', '반갑습니다~~221', 3, 0, to_date('08/08/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (222, '안녕하세요222', '반갑습니다~~222', 4, 0, to_date('08/09/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (223, '안녕하세요223', '반갑습니다~~223', 2, 0, to_date('08/10/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (224, '안녕하세요224', '반갑습니다~~224', 3, 0, to_date('08/11/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (225, '안녕하세요225', '반갑습니다~~225', 4, 0, to_date('08/12/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (226, '안녕하세요226', '반갑습니다~~226', 2, 0, to_date('08/13/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (227, '안녕하세요227', '반갑습니다~~227', 3, 0, to_date('08/14/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (228, '안녕하세요228', '반갑습니다~~228', 4, 0, to_date('08/15/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (229, '안녕하세요229', '반갑습니다~~229', 2, 0, to_date('08/16/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (230, '안녕하세요230', '반갑습니다~~230', 3, 0, to_date('08/17/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (231, '안녕하세요231', '반갑습니다~~231', 4, 0, to_date('08/18/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (232, '안녕하세요232', '반갑습니다~~232', 2, 0, to_date('08/19/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (233, '안녕하세요233', '반갑습니다~~233', 3, 0, to_date('08/20/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (234, '안녕하세요234', '반갑습니다~~234', 4, 0, to_date('08/21/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (235, '안녕하세요235', '반갑습니다~~235', 2, 0, to_date('08/22/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (236, '안녕하세요236', '반갑습니다~~236', 3, 0, to_date('08/23/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (237, '안녕하세요237', '반갑습니다~~237', 4, 0, to_date('08/24/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (238, '안녕하세요238', '반갑습니다~~238', 2, 0, to_date('08/25/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (239, '안녕하세요239', '반갑습니다~~239', 3, 0, to_date('08/26/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (240, '안녕하세요240', '반갑습니다~~240', 4, 0, to_date('08/27/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (241, '안녕하세요241', '반갑습니다~~241', 2, 0, to_date('08/28/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (242, '안녕하세요242', '반갑습니다~~242', 3, 0, to_date('08/29/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (243, '안녕하세요243', '반갑습니다~~243', 4, 0, to_date('08/30/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (244, '안녕하세요244', '반갑습니다~~244', 2, 0, to_date('08/31/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (245, '안녕하세요245', '반갑습니다~~245', 3, 0, to_date('09/01/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (246, '안녕하세요246', '반갑습니다~~246', 4, 0, to_date('09/02/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (247, '안녕하세요247', '반갑습니다~~247', 2, 0, to_date('09/03/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (248, '안녕하세요248', '반갑습니다~~248', 3, 0, to_date('09/04/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (249, '안녕하세요249', '반갑습니다~~249', 4, 0, to_date('09/05/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (250, '안녕하세요250', '반갑습니다~~250', 2, 0, to_date('09/06/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (251, '안녕하세요251', '반갑습니다~~251', 3, 0, to_date('09/07/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (252, '안녕하세요252', '반갑습니다~~252', 4, 0, to_date('09/08/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (253, '안녕하세요253', '반갑습니다~~253', 2, 0, to_date('09/09/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (254, '안녕하세요254', '반갑습니다~~254', 3, 0, to_date('09/10/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (255, '안녕하세요255', '반갑습니다~~255', 4, 0, to_date('09/11/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (256, '안녕하세요256', '반갑습니다~~256', 2, 0, to_date('09/12/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (257, '안녕하세요257', '반갑습니다~~257', 3, 0, to_date('09/13/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (258, '안녕하세요258', '반갑습니다~~258', 4, 0, to_date('09/14/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (259, '안녕하세요259', '반갑습니다~~259', 2, 0, to_date('09/15/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (260, '안녕하세요260', '반갑습니다~~260', 3, 0, to_date('09/16/2024', 'MM/DD/RRRR'), 5);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (261, '안녕하세요261', '반갑습니다~~261', 4, 0, to_date('09/17/2024', 'MM/DD/RRRR'), 2);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (262, '안녕하세요262', '반갑습니다~~262', 2, 0, to_date('09/18/2024', 'MM/DD/RRRR'), 3);

INSERT INTO COMMUNITY (COMMUNITY_NUMBER, COMMUNITY_TITLE, COMMUNITY_CONTENT, TAB_NUMBER, COMMUNITY_VIEWCOUNT, COMMUNITY_DATE, MEMBER_NUMBER) 
VALUES (263, '안녕하세요263', '반갑습니다~~263', 3, 0, to_date('09/19/2024', 'MM/DD/RRRR'), 4);

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (1, NULL, 263, 2, '퍼가요~~', to_date('08/24/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (2, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('08/25/2024', 'MM/DD/RRRR'), 1, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (3, NULL, 263, 4, '퍼가요~~', to_date('08/26/2024', 'MM/DD/RRRR'), 2, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (4, NULL, 260, 5, '좋은글 잘 보고 갑니다~~', to_date('08/27/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (5, NULL, 260, 2, '퍼가요~~', to_date('08/28/2024', 'MM/DD/RRRR'), 1, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (6, NULL, 258, 3, '좋은글 잘 보고 갑니다~~', to_date('08/29/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (7, NULL, 257, 4, '퍼가요~~', to_date('08/30/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (8, NULL, 256, 5, '좋은글 잘 보고 갑니다~~', to_date('08/31/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (9, NULL, 255, 2, '퍼가요~~', to_date('09/01/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (10, 9, 255, 3, '좋은글 잘 보고 갑니다~~', to_date('09/02/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (11, 9, 255, 4, '퍼가요~~', to_date('09/03/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (12, 11, 255, 5, '좋은글 잘 보고 갑니다~~', to_date('09/04/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (13, 11, 255, 2, '퍼가요~~', to_date('09/05/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (14, 11, 255, 3, '좋은글 잘 보고 갑니다~~', to_date('09/06/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (15, 13, 255, 4, '퍼가요~~', to_date('09/07/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (16, NULL, 252, 5, '좋은글 잘 보고 갑니다~~', to_date('09/08/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (17, NULL, 252, 2, '퍼가요~~', to_date('09/09/2024', 'MM/DD/RRRR'), 1, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (18, NULL, 250, 3, '좋은글 잘 보고 갑니다~~', to_date('09/10/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (19, NULL, 249, 4, '퍼가요~~', to_date('09/11/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (20, NULL, 248, 5, '좋은글 잘 보고 갑니다~~', to_date('09/12/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (21, NULL, 248, 2, '퍼가요~~', to_date('09/13/2024', 'MM/DD/RRRR'), 1, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (22, NULL, 248, 3, '좋은글 잘 보고 갑니다~~', to_date('09/14/2024', 'MM/DD/RRRR'), 2, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (23, NULL, 248, 4, '퍼가요~~', to_date('09/15/2024', 'MM/DD/RRRR'), 3, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (24, NULL, 246, 5, '좋은글 잘 보고 갑니다~~', to_date('09/16/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (25, NULL, 239, 2, '퍼가요~~', to_date('09/17/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (26, NULL, 238, 3, '좋은글 잘 보고 갑니다~~', to_date('09/18/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (27, NULL, 237, 4, '퍼가요~~', to_date('09/19/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (28, NULL, 236, 5, '좋은글 잘 보고 갑니다~~', to_date('09/20/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (29, NULL, 235, 2, '퍼가요~~', to_date('09/21/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (30, NULL, 234, 3, '좋은글 잘 보고 갑니다~~', to_date('09/22/2024', 'MM/DD/RRRR'), 0, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (31, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 3, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (32, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 4, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (33, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 5, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (34, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 6, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (35, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 7, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (36, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 8, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (37, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 9, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (38, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 10, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (39, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 11, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (40, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 12, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (41, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 13, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (42, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 14, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (43, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 15, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (44, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 16, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (45, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 17, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (46, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 18, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (47, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 19, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (48, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 20, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (49, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 21, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (50, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 22, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (51, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 23, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (52, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 24, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (53, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 25, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (54, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 26, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (55, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 27, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (56, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 28, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (57, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 29, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (58, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 30, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (59, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 31, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (60, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 32, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (61, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 33, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (62, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 34, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (63, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 35, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (64, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 36, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (65, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 37, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (66, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 38, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (67, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 39, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (68, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 40, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (69, NULL, 263, 4, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 41, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (70, NULL, 263, 5, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 42, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (71, NULL, 263, 2, '퍼가요~~', to_date('09/23/2024', 'MM/DD/RRRR'), 43, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_COMMENT (COMMUNITY_COMMENT_NUMBER, COMMUNITY_PARENT_NUMBER, COMMUNITY_NUMBER, MEMBER_NUMBER, COMMUNITY_COMMENT_CONTENT, COMMUNITY_COMMENT_DATE, COMMENT_GROUP, COMMENT_DEPTH, COMMENT_ORDER, COMMENT_CHILD_COUNT, COMMENT_STATUS) 
VALUES (72, NULL, 263, 3, '좋은글 잘 보고 갑니다~~', to_date('09/23/2024', 'MM/DD/RRRR'), 44, 0, 0, 0, 'Y');

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 263);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 263);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (4, 263);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (5, 263);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 262);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 261);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 261);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (4, 259);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (5, 259);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 258);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 258);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (4, 258);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 257);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 257);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 256);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 256);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 255);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 255);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (4, 255);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 254);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 254);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 253);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 253);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (4, 253);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (4, 252);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (5, 252);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (5, 251);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 250);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 249);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 248);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 247);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 246);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (4, 245);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 244);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 244);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 243);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 242);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 241);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 241);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (4, 241);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 240);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 240);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 239);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (2, 238);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 238);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (3, 237);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (4, 237);

INSERT INTO COMMUNITY_LIKE (MEMBER_NUMBER, COMMUNITY_NUMBER) 
VALUES (5, 237);


INSERT INTO CATEGORY
VALUES (1, '유머');
INSERT INTO CATEGORY
VALUES (2, '예술 / 문학');
INSERT INTO CATEGORY
VALUES (3, '세계');
INSERT INTO CATEGORY
VALUES (4, '역사');
INSERT INTO CATEGORY
VALUES (5, '언어');
INSERT INTO CATEGORY
VALUES (6, '과학 / 자연');
INSERT INTO CATEGORY
VALUES (7, '스포츠');
INSERT INTO CATEGORY
VALUES (8, '기타');

INSERT INTO QUIZ
VALUES (1, '인물이름맞추기', SYSDATE, SYSDATE, '야호', 1, 2, 'static/img/THUMBNAIL/quiz_1.webp');

INSERT INTO QUIZ
VALUES (2, '사람들이 사는 방법', SYSDATE, SYSDATE, '나는 나의 오호', 1, 1, 'static/img/THUMBNAIL/quiz_2.webp');

INSERT INTO QUIZ
VALUES (3, '태정태세문단세', SYSDATE, SYSDATE, '이게대체 무슨 소리야', 1, 3, 'static/img/THUMBNAIL/quiz_3.webp');

INSERT INTO QUIZ
VALUES (4, '끼얏호우 하핳하', SYSDATE, SYSDATE, '모두 다 죽어라!', 1, 2, 'static/img/THUMBNAIL/quiz_4.webp');

INSERT INTO QUIZ
VALUES (5, '나는 나다', SYSDATE, SYSDATE, '나는 나이기 때문이다.', 1, 4, 'static/img/THUMBNAIL/quiz_5.webp');

INSERT INTO QUIZ
VALUES (6, '너는 누구인가?', SYSDATE, SYSDATE, '나는 너가 아니기 때문에 모른다.', 1, 5, 'static/img/THUMBNAIL/quiz_6.webp');

INSERT INTO QUIZ
VALUES (7, '허ㅓ허ㅓㅓㅓ', SYSDATE, SYSDATE, 'ㅗㅕㅜㅏㅏㅓㅑㅏ,ㅜㅏㅝㅑㅜㅘ', 1, 6, 'static/img/THUMBNAIL/quiz_7.webp');

INSERT INTO QUIZ
VALUES (8, '세세ㅔㅔ셋ㄱ스', SYSDATE, SYSDATE, 'ㅅㄱ', 1, 7, 'static/img/THUMBNAIL/quiz_8.webp');

INSERT INTO QUIZ
VALUES (9, '수고바위', SYSDATE, SYSDATE, '머지했어요', 1, 8, 'static/img/THUMBNAIL/quiz_9.webp');

INSERT INTO QUIZ
VALUES (10, '아ㅏㅏㅏ앙ㅇ아ㅏ앙ㅇㅇ아ㅏ', SYSDATE, SYSDATE, '응기잇', 1, 3, 'static/img/THUMBNAIL/quiz_10.webp');

INSERT INTO QUIZ
VALUES (11, '하야다ㅜ야ㅏㅜ댜아ㅓㅎ', SYSDATE, SYSDATE, 'ㅁㅇㅍㄷㅎㄹ', 1, 2, 'static/img/THUMBNAIL/quiz_11.webp');

INSERT INTO QUIZ
VALUES (12, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_12.webp');

INSERT INTO QUIZ
VALUES (13, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_13.webp');

INSERT INTO QUIZ
VALUES (14, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_14.webp');

INSERT INTO QUIZ
VALUES (15, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_15.webp');

INSERT INTO QUIZ
VALUES (16, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_16.webp');

INSERT INTO QUIZ
VALUES (17, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_17.webp');

INSERT INTO QUIZ
VALUES (18, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_18.webp');

INSERT INTO QUIZ
VALUES (19, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_19.webp');

INSERT INTO QUIZ
VALUES (20, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_20.webp');

INSERT INTO QUIZ
VALUES (21, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_21.webp');

INSERT INTO QUIZ
VALUES (22, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, 'static/img/THUMBNAIL/quiz_22.webp');

INSERT INTO QUIZ_TAG
VALUES ('유머', 3);

INSERT INTO QUIZ_TAG
VALUES ('사람', 1);

INSERT INTO QUIZ_TAG
VALUES ('유머', 4);

INSERT INTO QUIZ_TAG
VALUES ('사람', 3);

INSERT INTO QUIZ_LOG
VALUES (1, 3, 1, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (2, 2, 1, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (3, 5, 1, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (4, 6, 3, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (5, 3, 3, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (6, 3, 1, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (7, 3, 4, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (8, 5, 5, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (9, 3, 22, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (10, 5, 21, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (11, 5, 11, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (12, 2, 6, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (13, 2, 1, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (14, 1, 13, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (15, 1, 6, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (16, 6, 7, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (17, 6, 11, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (18, 3, 19, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (19, 5, 13, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (20, 3, 20, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (21, 3, 11, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (22, 4, 14, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (23, 3, 12, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (24, 3, 11, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (25, 6, 8, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (26, 3, 5, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (27, 3, 9, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (28, 3, 6, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (29, 4, 4, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (30, 3, 1, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (31, 1, 8, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (32, 3, 4, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (33, 3, 3, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (34, 2, 9, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (35, 3, 6, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (36, 4, 17, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (37, 5, 12, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (38, 3, 9, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (39, 6, 4, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (40, 3, 8, 100, SYSDATE);
INSERT INTO QUIZ_LOG
VALUES (41, 1, 10, 100, SYSDATE);
COMMIT;

--ROLLBACK;