INSERT INTO CATEGORY
VALUES (1, '유머');
INSERT INTO CATEGORY
VALUES (2, '예술 / 문학');
INSERT INTO CATEGORY
VALUES (3, '세계');
INSERT INTO CATEGORY
VALUES (4, '역사');
INSERT INTO CATEGORY
VALUES (5, '언어');
INSERT INTO CATEGORY
VALUES (6, '과학 / 자연');
INSERT INTO CATEGORY
VALUES (7, '스포츠');
INSERT INTO CATEGORY
VALUES (8, '기타');

DROP SEQUENCE SEQ_QUIZ;

CREATE SEQUENCE SEQ_QUIZ
    INCREMENT BY 1
    START WITH 23;


INSERT INTO QUIZ
VALUES (1, '인물이름맞추기', SYSDATE, SYSDATE, '야호', 1, 2, '');
commit;

INSERT INTO QUIZ
VALUES (2, '사람들이 사는 방법', SYSDATE, SYSDATE, '나는 나의 오호', 1, 1, '');
INSERT INTO QUIZ
VALUES (3, '태정태세문단세', SYSDATE, SYSDATE, '이게대체 무슨 소리야', 1, 3, '');
INSERT INTO QUIZ
VALUES (4, '끼얏호우 하핳하', SYSDATE, SYSDATE, '모두 다 죽어라!', 1, 2, '');
INSERT INTO QUIZ
VALUES (5, '나는 나다', SYSDATE, SYSDATE, '나는 나이기 때문이다.', 1, 4, '');
INSERT INTO QUIZ
VALUES (6, '너는 누구인가?', SYSDATE, SYSDATE, '나는 너가 아니기 때문에 모른다.', 1, 5, '');
INSERT INTO QUIZ
VALUES (7, '허ㅓ허ㅓㅓㅓ', SYSDATE, SYSDATE, 'ㅗㅕㅜㅏㅏㅓㅑㅏ,ㅜㅏㅝㅑㅜㅘ', 1, 6, '');
INSERT INTO QUIZ
VALUES (8, '세세ㅔㅔ셋ㄱ스', SYSDATE, SYSDATE, 'ㅅㄱ', 1, 7, '');
INSERT INTO QUIZ
VALUES (9, '수고바위', SYSDATE, SYSDATE, '머지했어요', 1, 8, '');
INSERT INTO QUIZ
VALUES (10, '아ㅏㅏㅏ앙ㅇ아ㅏ앙ㅇㅇ아ㅏ', SYSDATE, SYSDATE, '응기잇', 1, 3, '');
INSERT INTO QUIZ
VALUES (11, '하야다ㅜ야ㅏㅜ댜아ㅓㅎ', SYSDATE, SYSDATE, 'ㅁㅇㅍㄷㅎㄹ', 1, 2, '');
INSERT INTO QUIZ
VALUES (12, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (13, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (14, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (15, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (16, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (17, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (18, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (19, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (20, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (21, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');
INSERT INTO QUIZ
VALUES (22, '라야추ㅏ얖', SYSDATE, SYSDATE, '무야호~~~', 1, 1, '');



COMMIT;

INSERT INTO QUIZ_TAG
VALUES ('유머', 3);

INSERT INTO QUIZ_TAG
VALUES ('사람', 1);

INSERT INTO QUIZ_TAG
VALUES ('유머', 4);

INSERT INTO QUIZ_TAG
VALUES ('사람', 3);

COMMIT;






