INSERT INTO CATEGORY
VALUES (1, '¿Ø∏”');
INSERT INTO CATEGORY
VALUES (2, 'øπº˙ / πÆ«–');
INSERT INTO CATEGORY
VALUES (3, 'ºº∞Ë');
INSERT INTO CATEGORY
VALUES (4, 'ø™ªÁ');
INSERT INTO CATEGORY
VALUES (5, 'ææÓ');
INSERT INTO CATEGORY
VALUES (6, '∞˙«– / ¿⁄ø¨');
INSERT INTO CATEGORY
VALUES (7, 'Ω∫∆˜√˜');
INSERT INTO CATEGORY
VALUES (8, '±‚≈∏');

CREATE SEQUENCE SEQ_QUIZ
    INCREMENT BY 1
    START WITH 1;

INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '¿Œπ∞¿Ã∏ß∏¬√ﬂ±‚', SYSDATE, SYSDATE, 'æﬂ»£', 1, 2, NULL);
commit;

INSERT INTO QUIZ_TAG
VALUES ('¿Ø∏”', 1);
INSERT INTO QUIZ_TAG
VALUES ('ªÁ∂˜', 1);
COMMIT;

INSERT INTO QUIZ
VALUES (SEQ_QUIZ, 'QWER', SYSDATE, SYSDATE, 1, 2);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '¿¿æ÷', SYSDATE, SYSDATE, 1, 1);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '≥¢æÊ»£øÏ', SYSDATE, SYSDATE, 1, 3);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '∑—∑—∑Œ', SYSDATE, SYSDATE, 1, 2);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, 'π´æﬂ»™', SYSDATE, SYSDATE, 1, 7);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '≤•»ƒ', SYSDATE, SYSDATE, 1, 6);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '§—æﬂ§ø¥Ÿ', SYSDATE, SYSDATE, 1, 5);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, 'æﬂ∏ﬁ∑Œ-!', SYSDATE, SYSDATE, 1, 4);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '¿∏æﬁæ÷§¿§∑', SYSDATE, SYSDATE, 1, 3);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, 'π«¿∏§—§æ', SYSDATE, SYSDATE, 1, 7);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»ÊS»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);
INSERT INTO QUIZ
VALUES (SEQ_QUIZ, '»Ê»Ê»Ê', SYSDATE, SYSDATE, 1, 8);


COMMIT;

INSERT INTO QUIZ_TAG
VALUES ('¿Ø∏”', 3);

INSERT INTO QUIZ_TAG
VALUES ('ªÁ∂˜', 1);

INSERT INTO QUIZ_TAG
VALUES ('¿Ø∏”', 4);

INSERT INTO QUIZ_TAG
VALUES ('ªÁ∂˜', 3);

COMMIT;






